config/routes.rb
Cinch2::Application.routes.draw do

 mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users, :controllers => { registrations: "signups"}
  root to: "static_pages#home"
  match '/about',         to: "static_pages#about"
  match '/faq',           to: "static_pages#faq"
  match '/project',       to: "static_pages#project"
  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post
  match 'upload' => 'uploads#new', :as => 'upload', :via => :get
  match 'upload' => 'uploads#create', :as => 'upload', :via => :post
  match 'crawl' => "crawls#new", :as => 'crawl', :via => :get
  match 'crawl' => "crawls#create", :as => 'crawl', :via => :post
  match '/crawl_results', to: "crawls#index"
  match '/download',      to: "downloads#index"

end

app/views/layouts/_error_messages.html.erb
<% if target.errors.any? %>
      <div class="alert-error">
      <ul>
      <% target.errors.full_messages.each do |msg| %>
         <li><%= msg %></li>
          <% end %>
          </ul>
      </div>
<% end %>

app/views/layouts/_form-convert.html.erb
<br /><br />
  <%= label_tag(:pdfa, "Convert PDF files to PDF/a: ") %>
  <%= check_box_tag(:pdfa)%>
<br />
  <%= label_tag(:jpeg2000, "Convert images to JPEG2000: ") %>
  <%= check_box_tag(:jpeg2000)%>
<br /><br />
<%= button_tag 'Submit', class: 'btn btn-primary' %>

app/views/layouts/_menu.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to "Cinch2", root_path, class: "brand" %>
      <div class="container nav-collapse">
        <ul class="nav">
          <li><%= link_to "About the Tool", about_path  %></li>
          <li><%= link_to "About the Project", project_path  %></li>
          <li><%= link_to "FAQ", faq_path  %></li>
          <li><%= link_to "Contact", contact_path  %></li>
          <% if user_signed_in? %>
              <li><%= link_to "Uploads", upload_path  %></li>
              <li><%= link_to "Crawl Url", crawl_path  %></li>
              <li><%= link_to "Crawl Results", crawl_results_path  %></li>
              <li><%= link_to "Download your Files", download_path  %></li>
              <% if can? :read, @admin %>
                  <li><%= link_to "Admin", '/admin'  %></li>
              <% end %>
              <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
          <% else %>
              <li>
                <%= link_to('Login', new_user_session_path)  %>
              </li>
          <% end %>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cinch2</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/menu' %>

<div id="mainwrap">
  <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "alert alert-#{key}") %>
  <% end %>
<%= yield %>
<div id="foot">
  <ul>
    <li><%= link_to image_tag("footerncdcr75.png", alt: "NCDCR Logo"), "http://ncdcr.gov" %></li>
    <li><%= link_to image_tag("footerslnc75.png", alt: "SLNC Logo"), "http://statelibrary.ncdcr.gov" %></li>
    <li><%= link_to image_tag("footernclive75.png", alt: "NCLIVE Logo"), "http://nclive.org" %></li>
    <li><%= link_to image_tag("IMLS_Logo.png", alt: "IMLS Logo"), "http://www.imls.gov" %></li>
  </ul>
</div>
  <%= debug(params) if Rails.env.development? %>
</div>
</body>
</html>

app/views/layouts/fluid.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Cinch2" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Cinch2</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
        <div class="row">
           <div class="span9">
              <%= yield %>
            </div>
            <div class="span3">
              <div class="well sidebar-nav">
                <h3>Sidebar</h3>
                <ul class="nav nav-list">
                  <li class="nav-header">Sidebar</li>
                  <li><%= link_to "Link1", "/path1"  %></li>
                  <li><%= link_to "Link2", "/path2"  %></li>
                  <li><%= link_to "Link3", "/path3"  %></li>
                </ul>
              </div><!--/.well -->
            </div><!--/span-->
        </div><!--/row-->
      </div><!--/content-->

      <footer>
        <p>&copy; Company 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>